"""Reference implementation of the paper batch-latency estimator.

This module provides a paper-aligned, side-effect-free batch-latency
estimator that is independent of the in-tree
:class:`sglang.srt.managers.lookahead_controller.BatchLatencyModel`
(which uses an online-fitted quadratic). The two are complementary —
:class:`BatchLatencyModel` learns from live measurements, while
:class:`BatchLatencyEstimator` exposes the closed-form expression used in
the paper for reasoning about admission decisions.

Paper formula (``eq:latency-model`` in Section ``sec:colocate``)::

    EstBatchLatency(B) = T_GEMM(M)
                       + α_d · Σ_{decode} L_j
                       + α_p · Σ_{prefill} A_j
    where M    = |B_decode| + Σ q_j
          A_j  = q_j · prefix_j + q_j · (q_j + 1) / 2

The default ``T_GEMM`` table reproduces the reference values used during
prototype validation. They are intentionally rough — production deployments
are expected to replace the table by an offline-profiled one for the target
GPU.
"""

from __future__ import annotations

import bisect
import dataclasses
from typing import Dict, Iterable, List, Optional, Sequence, Tuple


# ---------------------------------------------------------------------------
# Public dataclasses
# ---------------------------------------------------------------------------


@dataclasses.dataclass
class DecodeRequest:
    """Minimal view of a decode request needed by the estimator."""

    kv_cache_len: int
    """Length of the existing KV cache that the decode token attends to."""


@dataclasses.dataclass
class PrefillChunk:
    """Minimal view of a prefill chunk needed by the estimator."""

    chunk_tokens: int
    """``q_j`` — number of new tokens prefilled in this chunk."""

    prefix_kv_len: int = 0
    """``prefix_j`` — KV cache length already present at chunk start."""


@dataclasses.dataclass
class BatchLatencyEstimatorConfig:
    """Configuration for :class:`BatchLatencyEstimator`.

    The defaults below are **calibrated for Qwen3-8B on H100 80GB**, fit
    via single-request prefill + decode probes (see
    ``scripts/experiments/calibrate_estimator.py``). Re-fit on a different
    model / GPU before relying on them for SLO-aware admission.
    """

    # Recalibrated 2026-05-11 against single-request probe on Qwen3-8B/H100
    # (scripts/experiments/calibrate_estimator.py, run /tmp/calib_probe.jsonl):
    #   q=8192 single forward ≈ 451ms ≈ T_GEMM(8192)=13 + α_p × 33.5M
    #   → α_p ≈ 1.3e-5 to match q=8192; α_p ≈ 5e-6 averages well across q.
    # Default α_p was 2.4e-7 (~20x too low), causing the admission gate to
    # under-estimate batch latency and not bind.
    alpha_d: float = 6.50e-4
    """``α_d`` — milliseconds per decode KV token attended to.

    Calibrated 2026-04-29 on Qwen3-8B / single H100, with KV lengths up
    to 8K tokens. Fit residual: ≤ 2 ms across the sweep.
    """

    alpha_p: float = 5.00e-6
    """``α_p`` — milliseconds per unit of prefill attention work ``A_j``.

    Calibrated 2026-04-29 on Qwen3-8B / single H100, with prompt lengths
    8 → 8K tokens. Fit residual: ≤ 0.6 ms across the sweep.
    """

    gemm_table: Optional[Dict[int, float]] = None
    """Lookup table mapping forward-token count ``M`` to GEMM latency (ms).

    If ``None``, :func:`default_gemm_table` is used. The default table is
    the ``eq:latency-model`` shape; for production use
    on a specific GPU, replace with offline-profiled values.
    """


def default_gemm_table() -> Dict[int, float]:
    """Reference GEMM-latency table in milliseconds.

    These are reference values, useful for validating the formula
    shape but **not** calibrated for any specific GPU/model. Production
    deployments should use a model-specific table such as
    :func:`default_gemm_table_qwen3_8b_h100`.
    """
    return {
        1: 0.08,
        2: 0.08,
        4: 0.09,
        8: 0.10,
        16: 0.12,
        32: 0.18,
        64: 0.30,
        128: 0.55,
        256: 1.00,
        512: 1.90,
        1024: 3.70,
    }


def default_gemm_table_qwen3_8b_h100() -> Dict[int, float]:
    """Calibrated GEMM table for Qwen3-8B running on a single H100 80GB.

    Generated by ``scripts/experiments/calibrate_estimator.py`` on
    2026-04-29 (single-request prefill probe, baseline RTT subtracted,
    ``α_p`` solved jointly). Values are GPU-side only — they exclude
    HTTP transport and tokenization overhead.
    """
    return {
        1: 0.05,
        8: 0.20,
        32: 0.35,
        128: 0.55,
        512: 0.85,
        1024: 1.12,
        2048: 3.08,
        4096: 7.23,
        8192: 13.30,
    }


# ---------------------------------------------------------------------------
# Estimator
# ---------------------------------------------------------------------------


class BatchLatencyEstimator:
    """Closed-form ``EstBatchLatency(B)`` from ``eq:latency-model``.

    The estimator is purely functional: it does not store any state
    between calls and is safe to share across threads.
    """

    def __init__(self, config: Optional[BatchLatencyEstimatorConfig] = None) -> None:
        self.config = config or BatchLatencyEstimatorConfig()
        table = self.config.gemm_table or default_gemm_table()
        if not table:
            raise ValueError("gemm_table must contain at least one entry")
        self._gemm_keys: List[int] = sorted(table.keys())
        self._gemm_values: List[float] = [float(table[k]) for k in self._gemm_keys]

    # -- Public API ---------------------------------------------------------

    def estimate(
        self,
        decodes: Sequence[DecodeRequest] = (),
        prefill_chunks: Sequence[PrefillChunk] = (),
    ) -> float:
        """Return the predicted batch latency in milliseconds."""
        m = self.forward_token_count(decodes, prefill_chunks)
        return (
            self.gemm_cost(m)
            + self.config.alpha_d * self.decode_attention_cost(decodes)
            + self.config.alpha_p * self.prefill_attention_work(prefill_chunks)
        )

    # -- Component helpers (also used by tests) ----------------------------

    @staticmethod
    def forward_token_count(
        decodes: Sequence[DecodeRequest],
        prefill_chunks: Sequence[PrefillChunk],
    ) -> int:
        return len(decodes) + sum(int(c.chunk_tokens) for c in prefill_chunks)

    @staticmethod
    def decode_attention_cost(decodes: Sequence[DecodeRequest]) -> int:
        return sum(int(r.kv_cache_len) for r in decodes)

    @staticmethod
    def prefill_attention_work(prefill_chunks: Sequence[PrefillChunk]) -> int:
        total = 0
        for chunk in prefill_chunks:
            q = int(chunk.chunk_tokens)
            prefix = int(chunk.prefix_kv_len)
            total += q * prefix + q * (q + 1) // 2
        return total

    def gemm_cost(self, m: int) -> float:
        """Look up ``T_GEMM(m)`` with linear interpolation."""
        if m <= self._gemm_keys[0]:
            return self._gemm_values[0]
        if m >= self._gemm_keys[-1]:
            # Extrapolate linearly from the last two anchor points.
            x0, x1 = self._gemm_keys[-2], self._gemm_keys[-1]
            y0, y1 = self._gemm_values[-2], self._gemm_values[-1]
            return y1 + (y1 - y0) * (m - x1) / max(1, x1 - x0)
        idx = bisect.bisect_left(self._gemm_keys, m)
        if self._gemm_keys[idx] == m:
            return self._gemm_values[idx]
        x0, x1 = self._gemm_keys[idx - 1], self._gemm_keys[idx]
        y0, y1 = self._gemm_values[idx - 1], self._gemm_values[idx]
        ratio = (m - x0) / (x1 - x0)
        return y0 + ratio * (y1 - y0)

    # -- Diagnostics --------------------------------------------------------

    def predicted_vs_measured_mape(
        self,
        samples: Iterable[Tuple[Sequence[DecodeRequest], Sequence[PrefillChunk], float]],
    ) -> float:
        """Return mean absolute percentage error against measured latencies.

        Each ``samples`` entry is ``(decodes, prefill_chunks, measured_ms)``.
        """
        ratios = []
        for decodes, chunks, measured in samples:
            measured = float(measured)
            if measured <= 0:
                continue
            predicted = self.estimate(decodes, chunks)
            ratios.append(abs(predicted - measured) / measured)
        if not ratios:
            return 0.0
        return sum(ratios) / len(ratios) * 100.0
